# Generated by Django 5.1.1 on 2025-01-21 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_category_inventoryitem_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
