# Generated by Django 5.1.1 on 2025-01-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_remove_inventoryitem_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=7)),
            ],
        ),
    ]
