# Generated by Django 5.1.1 on 2025-01-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(),
        ),
    ]
